spring.application.name=mtcs
spring.datasource.url=jdbc:mysql://localhost:3306/mtcs
spring.datasource.username=root
spring.datasource.password=vsk@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=mysupersecretkeymysupersecretkey
app.jwt.expirationTime=3600000